version: "2"
services:
    backend:
        container_name: extractor_rest 
        image: extractor_rest:v1 
        build: .
        ports:
            - "5000:5000"
    mongo:
        container_name: mongo
        image: mongo:4.2.0
        ports:
            - "1048:27017"