apiVersion: v1
kind: Service
metadata:
  name: extract-worker-{model} 
  labels:
    type: public
    service: extract-worker
spec:
  selector:
    app: extract-worker-{model}
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: extract-worker-{model}
spec:
  replicas: {num_pods} 
  selector:
    matchLabels:
      app: extract-worker-{model}
  template:
    metadata:
      labels:
        app: extract-worker-{model}
    spec:
      containers:
      - name: extract-worker-{model}
        image: eu.gcr.io/gothic-module-289816/extract_worker 
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: myclaim 
            mountPath: /usr/app/tmp
        env:
        - name: ML_MODEL 
          value: "{model}"
        - name: MODEL_URL
          value: "{model_url}"
        - name: DEDUPLICATE_MODEL
          value: "{deduplicate_model}"
        - name: DEDUPLICATE_THRESHOLD
          value: "{deduplicate_threshold}"
      volumes:
        - name: myclaim 
          persistentVolumeClaim:
            claimName: myclaim
