apiVersion: v1
kind: Service
metadata:
  name: serving 
  labels:
    type: public
spec:
  selector:
    app: serving 
  ports:
  - protocol: "TCP"
    port: 8081 
    targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: serving 
spec:
  replicas: {num_pods} 
  selector:
    matchLabels:
      app: serving 
  template:
    metadata:
      labels:
        app: serving 
    spec:
      containers:
      - name: serving 
        image: eu.gcr.io/gothic-module-289816/nginx:latest 
        imagePullPolicy: Always 
        ports:
        - containerPort: 8081
        volumeMounts:
          - name: nginx-conf 
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf 
          configMap:
            defaultMode: 420
            name: nginx-conf 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    upstream loadbalancer {
        {servers}
    }
    server {
        listen      8081;
        location / {
            proxy_pass http://loadbalancer;
        }
    } 