global:
    scrape_interval: 5s
    scrape_timeout: 2s
  
  rule_files:
    - alert.yml
  
  scrape_configs:
{jobs}
    # - job_name: index_services
    #   metrics_path: /metrics
    #   static_configs:
    #     - targets:
    #         - 'indexing-mobilenet-1-mongo.rahtiapp.fi'
    #         # - 'indexing-mobilenet-2-mongo.rahtiapp.fi'
    #         - 'indexing-resnet-1-mongo.rahtiapp.fi'
    #         # - 'indexing-resnet-2-mongo.rahtiapp.fi'
    #         - 'indexing-custom-1-mongo.rahtiapp.fi'
    #         # - 'indexing-custom-2-mongo.rahtiapp.fi'
    # - job_name: extract_worker_services
    #   metrics_path: /metrics
    #   static_configs:
    #     - targets:
    #         - 'extract-worker-custom-mongo.rahtiapp.fi'
    #         - 'extract-worker-resnet-mongo.rahtiapp.fi'
    #         - 'extract-worker-mobilenet-mongo.rahtiapp.fi'
    # - job_name: serving_services 
    #   metrics_path: /metrics
    #   static_configs:
    #     - targets:
    #         - 'serving-mobilenet-mongo.rahtiapp.fi'
    #         - 'serving-resnet-mongo.rahtiapp.fi'
    #         - 'serving-custom-mongo.rahtiapp.fi'