apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
        scrape_interval: 5s
        scrape_timeout: 2s
    # rule_files:
    #   - alert.yml
    scrape_configs:
{jobs}