apiVersion: v1
kind: Service
metadata:
  name: serving-{model} 
spec:
  selector:
    app: serving-{model}
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: serving-{model}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: serving-{model} 
  template:
    metadata:
      labels:
        app: serving-{model} 
    spec:
      containers:
      - name: serving-{model} 
        image: zozonguyen/serving:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: file-claim
            mountPath: /usr/app/files
        env:
        - name: TOTAL_NUM_INDEXES 
          value: "{num_indexes}"
        - name: ML_MODEL 
          value: "{model}"

  volumeClaimTemplates:
  - metadata:
      name: file-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi