apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: extract-worker 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: extract-worker 
  template:
    metadata:
      labels:
        app: extract-worker 
    spec:
      containers:
      - name: extract-worker 
        image: zozonguyen/extract_worker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: file-claim
            mountPath: /usr/app/tmp
        env:
        - name: ML_MODEL 
          value: "resnet"
        - name: TOTAL_NUM_INDEXES 
          value: "2"

  volumeClaimTemplates:
  - metadata:
      name: file-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi