kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: extract-worker-resnet
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: extract-worker-resnet
  template:
    metadata:
      labels:
        app: extract-worker-resnet
    spec:
      containers:
      - name: extract-worker-resnet
        image: eu.gcr.io/gothic-module-289816/extract_worker 
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: myclaim 
            mountPath: /usr/app/tmp
        env:
        - name: ML_MODEL 
          value: "resnet"
        - url: CUSTOM_MODEL_URL
          value: ""
      volumes:
        - name: myclaim 
          persistentVolumeClaim:
            claimName: myclaim
