apiVersion: v1
kind: Service
metadata:
  name: indexing-resnet-1 
spec:
  selector:
    app: indexing-resnet-1 
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: indexing-resnet-1 
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: indexing-resnet-1 
  template:
    metadata:
      labels:
        app: indexing-resnet-1 
        service: indexing
    spec:
      containers:
      - name: indexing-resnet-1 
        image: eu.gcr.io/gothic-module-289816/indexing:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: TOTAL_NUM_INDEXES 
          value: "1"
        - name: CURRENT_INDEX 
          value: "1"
        - name: ML_MODEL 
          value: "resnet" 
        - name: MODEL_URL 
          value: "" 
        - name: INDEX_ALGORITHM
          value: "brute"
