global:
    scrape_interval: 5s
    scrape_timeout: 2s
  
  rule_files:
    - alert.yml
  
  scrape_configs:
    - job_name: extract-worker-custom
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-custom-59b85b569d-826s5.extract-worker-custom.mongo.svc.cluster.local:5000'
            - 'extract-worker-custom-6cfd5655c-qsgmg.extract-worker-custom.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-mobilenet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-mobilenet-644c869fbc-8fh6r.extract-worker-mobilenet.mongo.svc.cluster.local:5000'
            - 'extract-worker-mobilenet-8658875886-z7kvz.extract-worker-mobilenet.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-resnet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-resnet-58c6b847d7-6bmv5.extract-worker-resnet.mongo.svc.cluster.local:5000'
            - 'extract-worker-resnet-8d7675dc4-zh7wc.extract-worker-resnet.mongo.svc.cluster.local:5000'

    - job_name: indexing-custom-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-custom-1-79bb949578-fhvl5.indexing-custom-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-mobilenet-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-mobilenet-1-6c776fc887-849j9.indexing-mobilenet-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-resnet-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-resnet-1-d5cf5f8bf-6s9bp.indexing-resnet-1.mongo.svc.cluster.local:5000'
            - 'indexing-resnet-1-d5cf5f8bf-ctfrx.indexing-resnet-1.mongo.svc.cluster.local:5000'
            - 'indexing-resnet-1-d5cf5f8bf-hgthj.indexing-resnet-1.mongo.svc.cluster.local:5000'
            - 'indexing-resnet-1-d5cf5f8bf-m4m2k.indexing-resnet-1.mongo.svc.cluster.local:5000'
            - 'indexing-resnet-1-d5cf5f8bf-v54hr.indexing-resnet-1.mongo.svc.cluster.local:5000'

    - job_name: serving-custom
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-custom-767d6474c6-c72lj.serving-custom.mongo.svc.cluster.local:5000'
            - 'serving-custom-767d6474c6-pjj8h.serving-custom.mongo.svc.cluster.local:5000'
            - 'serving-custom-767d6474c6-r24bm.serving-custom.mongo.svc.cluster.local:5000'

    - job_name: serving-mobilenet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-mobilenet-556957cc7-b2gvq.serving-mobilenet.mongo.svc.cluster.local:5000'
            - 'serving-mobilenet-556957cc7-cgzww.serving-mobilenet.mongo.svc.cluster.local:5000'
            - 'serving-mobilenet-556957cc7-shgpm.serving-mobilenet.mongo.svc.cluster.local:5000'

    - job_name: serving-resnet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-resnet-57ffd6cd7f-hjdsz.serving-resnet.mongo.svc.cluster.local:5000'
            - 'serving-resnet-57ffd6cd7f-nqfld.serving-resnet.mongo.svc.cluster.local:5000'
            - 'serving-resnet-57ffd6cd7f-t5xck.serving-resnet.mongo.svc.cluster.local:5000'
            - 'serving-resnet-57ffd6cd7f-tv7k5.serving-resnet.mongo.svc.cluster.local:5000'
            - 'serving-resnet-57ffd6cd7f-zldmr.serving-resnet.mongo.svc.cluster.local:5000'


    # - job_name: index_services
    #   metrics_path: /metrics
    #   static_configs:
    #     - targets:
    #         - 'indexing-mobilenet-1-mongo.rahtiapp.fi'
    #         # - 'indexing-mobilenet-2-mongo.rahtiapp.fi'
    #         - 'indexing-resnet-1-mongo.rahtiapp.fi'
    #         # - 'indexing-resnet-2-mongo.rahtiapp.fi'
    #         - 'indexing-custom-1-mongo.rahtiapp.fi'
    #         # - 'indexing-custom-2-mongo.rahtiapp.fi'
    # - job_name: extract_worker_services
    #   metrics_path: /metrics
    #   static_configs:
    #     - targets:
    #         - 'extract-worker-custom-mongo.rahtiapp.fi'
    #         - 'extract-worker-resnet-mongo.rahtiapp.fi'
    #         - 'extract-worker-mobilenet-mongo.rahtiapp.fi'
    # - job_name: serving_services 
    #   metrics_path: /metrics
    #   static_configs:
    #     - targets:
    #         - 'serving-mobilenet-mongo.rahtiapp.fi'
    #         - 'serving-resnet-mongo.rahtiapp.fi'
    #         - 'serving-custom-mongo.rahtiapp.fi'