apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
        scrape_interval: 5s
        scrape_timeout: 2s
    # rule_files:
    #   - alert.yml
    scrape_configs:
    - job_name: extract-worker-custom
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-custom-6f5cd5b4f-nmn89.extract-worker-custom.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-inception
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-inception-869857574b-mrx7x.extract-worker-inception.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-mobilenet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-mobilenet-55694db55b-js8kr.extract-worker-mobilenet.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-resnet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-resnet-8bbbd5dcb-h2pxj.extract-worker-resnet.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-vgg16
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-vgg16-7c46f68b74-hf4b2.extract-worker-vgg16.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-vgg19
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'extract-worker-vgg19-649b57d559-mvlbf.extract-worker-vgg19.mongo.svc.cluster.local:5000'

    - job_name: indexing-custom-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-custom-1-79bb949578-nrj78.indexing-custom-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-inception-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-inception-1-756994568f-tvqmp.indexing-inception-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-mobilenet-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-mobilenet-1-6c776fc887-fr4cj.indexing-mobilenet-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-resnet-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-resnet-1-d5cf5f8bf-bzp2l.indexing-resnet-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-vgg16-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-vgg16-1-567454d85c-tzf2c.indexing-vgg16-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-vgg19-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-vgg19-1-65f98bf664-8c5fk.indexing-vgg19-1.mongo.svc.cluster.local:5000'

    - job_name: serving-custom
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-custom-767d6474c6-skj9m.serving-custom.mongo.svc.cluster.local:5000'

    - job_name: serving-inception
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-inception-7d55766cff-hcf6c.serving-inception.mongo.svc.cluster.local:5000'

    - job_name: serving-mobilenet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-mobilenet-556957cc7-dj7cr.serving-mobilenet.mongo.svc.cluster.local:5000'

    - job_name: serving-resnet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-resnet-57ffd6cd7f-4cdsm.serving-resnet.mongo.svc.cluster.local:5000'

    - job_name: serving-vgg16
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-vgg16-6d6f87787f-csjjz.serving-vgg16.mongo.svc.cluster.local:5000'

    - job_name: serving-vgg19
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-vgg19-55d58cddb4-86flf.serving-vgg19.mongo.svc.cluster.local:5000'

