apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
        scrape_interval: 5s
        scrape_timeout: 2s
    # rule_files:
    #   - alert.yml
    scrape_configs:
    - job_name: extract-worker-custom
      metrics_path: /metrics
      static_configs:
        - targets:
            - '.extract-worker-custom.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-inception
      metrics_path: /metrics
      static_configs:
        - targets:
            - '.extract-worker-inception.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-mobilenet
      metrics_path: /metrics
      static_configs:
        - targets:
            - '.extract-worker-mobilenet.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-resnet
      metrics_path: /metrics
      static_configs:
        - targets:
            - '.extract-worker-resnet.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-vgg16
      metrics_path: /metrics
      static_configs:
        - targets:
            - '.extract-worker-vgg16.mongo.svc.cluster.local:5000'

    - job_name: extract-worker-vgg19
      metrics_path: /metrics
      static_configs:
        - targets:
            - '.extract-worker-vgg19.mongo.svc.cluster.local:5000'

    - job_name: indexing-custom-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-custom-1-7c64687d5d-cqzks.indexing-custom-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-inception-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-inception-1-cc4857657-b52zg.indexing-inception-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-mobilenet-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-mobilenet-1-7c5c7c4575-zr6kn.indexing-mobilenet-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-resnet-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-resnet-1-55874794b9-fd925.indexing-resnet-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-vgg16-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-vgg16-1-56d8b5d9df-b922m.indexing-vgg16-1.mongo.svc.cluster.local:5000'

    - job_name: indexing-vgg19-1
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'indexing-vgg19-1-f97b7b664-8vq7q.indexing-vgg19-1.mongo.svc.cluster.local:5000'

    - job_name: serving-custom
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-custom-767d6474c6-8qnvv.serving-custom.mongo.svc.cluster.local:5000'

    - job_name: serving-inception
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-inception-7d55766cff-rjttv.serving-inception.mongo.svc.cluster.local:5000'

    - job_name: serving-mobilenet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-mobilenet-556957cc7-g5wfx.serving-mobilenet.mongo.svc.cluster.local:5000'

    - job_name: serving-resnet
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-resnet-57ffd6cd7f-7qjzl.serving-resnet.mongo.svc.cluster.local:5000'

    - job_name: serving-vgg16
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-vgg16-6d6f87787f-9hfct.serving-vgg16.mongo.svc.cluster.local:5000'

    - job_name: serving-vgg19
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'serving-vgg19-55d58cddb4-jdrp4.serving-vgg19.mongo.svc.cluster.local:5000'

