apiVersion: v1
kind: Service
metadata:
  name: daas
spec:
  selector:
    name: daas
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: daas
  labels:
    name: daas
spec:
  serviceName: "daas"
  replicas: 2
  selector:
    matchLabels:
      name: daas
  template:
    metadata:
      labels:
        name: daas
    spec:
      containers:
      - name: daas
        image: daas
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: file-claim
          mountPath: /app/files
  volumeClaimTemplates:
  - metadata:
      name: file-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi